### ISSUE TITLE
Базовые сценарии

### ISSUE THREAD

**Issue by ctizen** [MahjongPantheon/Mimir#12]
Описаны основные сценарии, поддерживаемые так или иначе в предыдущей версии. Никаких уточнений по конкретике реализации не предлагается. Список нужен лишь для того, чтобы ничего не забыть. Для всех пунктов списка должны быть точки входа в api.
- [x] Добавление игрока
- [x] Добавление игры в текстовом режиме
- [x] Добавление игры в автоматическом режиме (с тенхонета)
- [x] Просмотр рейтинговой таблицы с сортировкой по имени, рейтингу, среднему месту
- [x] Просмотр логов последних игр
- [x] Просмотр статистики и графиков конкретных игроков
- [ ] Особые номинации для турниров
- [x] Авто-рассадка игроков в рамках турнира
- [x] Таймер (?)
- [ ] Возможность стартовать турнирные онлайн-игры (интеграция на чат и прочее)

Новые сценарии, которых в предыдущей версии не было по определенным причинам:
- [ ] Самостоятельная регистрация и авторизация игроков, в т.ч. через соцсети.
- [x] Добавление игры в интерактивном режиме, по одной раздаче за раз.
- [ ] Профиль игрока, статистика между турнирами и евентами
- [ ] Клубы и объединения: возможность создать свой клуб, назначить администраторов
- [ ] События: турниры, локальные рейтинги и прочее. Возможность создать и провести событие от лица организации либо конкретного игрока.
- [ ] Управление правилами стола: создание наборов правил, проведение событий согласно конкретным наборам.
  ...

**Comment by ctizen** [comment]
Перенесено в youtrack
